#!/usr/bin/bash
run_hook() {
    msg ":: PlayOS: configuring network..."
    for iface in /sys/class/net/*; do
        name="${iface##*/}"
        [ "$name" = "lo" ] && continue
        msg ":: Bringing up $name..."
        busybox ip link set "$name" up
        msg ":: $name state: $(cat /sys/class/net/$name/operstate)"
        msg ":: Trying DHCP on $name..."
        if busybox udhcpc -i "$name" -t 10 -n; then
            msg ":: DHCP succeeded on $name"
            return 0
        fi
        msg ":: DHCP failed on $name, trying next..."
    done
    msg ":: WARNING: No DHCP on any interface, continuing..."
    return 0
}
