#!/usr/bin/env bash
# setup-pxe-server.sh — Configure Ubuntu Server as a PlayOS PXE netboot host.
#
# Installs and configures:
#   - nginx: HTTP server for kernel, initramfs, modloop, and apkovl
#   - dnsmasq: DHCP proxy (adds PXE options to existing DHCP) + TFTP
#   - iPXE: UEFI chain-loader served via TFTP
#
# Architecture:
#   PXE client → DHCP (router + dnsmasq proxy adds PXE opts)
#              → TFTP load ipxe.efi
#              → iPXE DHCP (dnsmasq returns boot.ipxe filename)
#              → TFTP load boot.ipxe
#              → HTTP load kernel + initramfs from nginx
#
# Prerequisites:
#   - Ubuntu Server with the same subnet as PXE clients
#   - Existing DHCP server on the network (router)
#   - build-iso-ubuntu.sh has been run at least once to populate
#     /var/www/html/playos/ with kernel, initramfs, modloop, and apkovl
#
# Usage:
#   sudo bash scripts/setup-pxe-server.sh
#
# Overrides:
#   PXE_IFACE      Network interface for dnsmasq (auto-detected if unset)
#   PXE_HTTP_PORT  nginx listen port (default: 80)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Detect network interface ─────────────────────────────────────────────
if [[ -z "${PXE_IFACE:-}" ]]; then
    PXE_IFACE=$(ip -br addr show | grep -v 'lo\|docker\|DOWN' | awk '{print $1}' | head -1)
fi
if [[ -z "$PXE_IFACE" ]]; then
    echo "error: could not detect network interface; set PXE_IFACE" >&2
    exit 1
fi

SERVER_IP=$(ip -4 addr show "$PXE_IFACE" | grep -oP 'inet \K[\d.]+' | head -1)
if [[ -z "$SERVER_IP" ]]; then
    echo "error: could not detect IP on $PXE_IFACE" >&2
    exit 1
fi

HTTP_PORT="${PXE_HTTP_PORT:-80}"
TFTP_ROOT="/srv/tftp"
WEB_ROOT="/var/www/html"
PLAYOS_URL_BASE="/playos"

echo "=== PlayOS PXE Server Setup ==="
echo "Interface : $PXE_IFACE"
echo "Server IP : $SERVER_IP"
echo "HTTP port : $HTTP_PORT"
echo "TFTP root : $TFTP_ROOT"
echo "Web root  : $WEB_ROOT"

# ── Install packages ─────────────────────────────────────────────────────
echo ""
echo "==> Installing packages"
sudo apt-get update -qq
sudo apt-get install -y -qq nginx dnsmasq ipxe

# ── Deploy iPXE UEFI binary to TFTP root ─────────────────────────────────
echo ""
echo "==> Deploying iPXE EFI binary"
sudo mkdir -p "$TFTP_ROOT"

IPXE_EFI=""
for candidate in \
    /usr/lib/ipxe/ipxe.efi \
    /usr/share/ipxe/ipxe.efi \
    /boot/ipxe.efi; do
    if [[ -f "$candidate" ]]; then
        IPXE_EFI="$candidate"
        break
    fi
done

if [[ -z "$IPXE_EFI" ]]; then
    echo "error: could not find ipxe.efi binary" >&2
    echo "Tried: /usr/lib/ipxe/ipxe.efi, /usr/share/ipxe/ipxe.efi, /boot/ipxe.efi" >&2
    exit 1
fi

sudo cp "$IPXE_EFI" "$TFTP_ROOT/ipxe.efi"
sudo chmod 0644 "$TFTP_ROOT/ipxe.efi"
echo "    $IPXE_EFI → $TFTP_ROOT/ipxe.efi"

# ── Deploy iPXE boot script to TFTP root ─────────────────────────────────
echo "==> Deploying iPXE boot script"
sudo cp "$ROOT/alpine/boot.ipxe" "$TFTP_ROOT/boot.ipxe"
sudo chmod 0644 "$TFTP_ROOT/boot.ipxe"
echo "    $ROOT/alpine/boot.ipxe → $TFTP_ROOT/boot.ipxe"

# Also deploy to web root for HTTP access (USB fallback + reference)
sudo mkdir -p "$WEB_ROOT$PLAYOS_URL_BASE"
sudo cp "$ROOT/alpine/boot.ipxe" "$WEB_ROOT$PLAYOS_URL_BASE/boot.ipxe"
sudo chmod 0644 "$WEB_ROOT$PLAYOS_URL_BASE/boot.ipxe"
echo "    $ROOT/alpine/boot.ipxe → $WEB_ROOT$PLAYOS_URL_BASE/boot.ipxe"

# ── Configure dnsmasq (DHCP proxy + TFTP) ────────────────────────────────
echo ""
echo "==> Configuring dnsmasq"
sudo mkdir -p /etc/dnsmasq.d

sudo tee /etc/dnsmasq.d/playos-pxe.conf > /dev/null <<DNSMASQ
# PlayOS PXE — DHCP proxy + TFTP
# Binds to: $PXE_IFACE
# Generated by: scripts/setup-pxe-server.sh

# Disable DNS (systemd-resolved handles it)
port=0

# DHCP proxy mode: add PXE options without replacing the existing DHCP server.
# Covers the entire /24 subnet. Adjust if your network uses a different mask.
dhcp-range=${SERVER_IP%.*}.0,proxy,255.255.255.0

# Log DHCP requests for debugging
log-dhcp

# ── Client architecture matching ─────────────────────────────────────────
# Arch 7: x86_64 UEFI
# Arch 9: x86_64 UEFI with HTTP boot capability
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-match=set:efi-x86_64,option:client-arch,9
dhcp-match=set:bios-x86,option:client-arch,0

# ── First stage: PXE firmware loads iPXE ─────────────────────────────────
# Tag !ipxe: only match before iPXE takes over (iPXE sets user-class "iPXE")
dhcp-boot=tag:efi-x86_64,tag:!ipxe,ipxe.efi

# ── Second stage: iPXE loads boot script ─────────────────────────────────
# iPXE sets user-class "iPXE" in its own DHCP request.
# Return "boot.ipxe" as the filename — iPXE fetches it from TFTP.
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,boot.ipxe

# ── TFTP ─────────────────────────────────────────────────────────────────
enable-tftp
tftp-root=$TFTP_ROOT
DNSMASQ

# Disable the default dnsmasq config (it binds port 53 which conflicts)
if [[ -f /etc/dnsmasq.conf ]]; then
    sudo sed -i 's/^/#/' /etc/dnsmasq.conf
fi

# ── Configure nginx ──────────────────────────────────────────────────────
echo ""
echo "==> Configuring nginx"

# Create/overwrite the default site
sudo tee /etc/nginx/sites-available/default > /dev/null <<'NGINX'
# PlayOS PXE — HTTP server for kernel, initramfs, modloop, apkovl
# Generated by: scripts/setup-pxe-server.sh

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    # Enable directory listing for the PXE directory (useful for debugging)
    location /playos/ {
        autoindex on;
    }

    # Proper MIME types for PXE artifacts
    types {
        application/octet-stream  img img.zst iso;
        application/gzip          gz;
        application/x-tar         tar;
        text/plain                sha256 ipxe;
    }
}
NGINX

# Ensure the web root exists
sudo mkdir -p "$WEB_ROOT$PLAYOS_URL_BASE"

# ── Start/enable services ────────────────────────────────────────────────
echo ""
echo "==> Starting services"

# Stop systemd-resolved from holding port 53 (dnsmasq uses port=0, but just in case)
# systemd-resolved is fine — we use port=0 in dnsmasq

sudo systemctl enable nginx --quiet
sudo systemctl restart nginx

sudo systemctl enable dnsmasq --quiet
sudo systemctl restart dnsmasq 2>&1 || {
    echo "WARNING: dnsmasq failed to start — checking config..."
    sudo dnsmasq --test --conf-file=/etc/dnsmasq.d/playos-pxe.conf 2>&1 || true
    sudo journalctl -u dnsmasq --no-pager -n 20
}

# ── Open firewall (if ufw is active) ─────────────────────────────────────
if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q 'Status: active'; then
    echo ""
    echo "==> Configuring firewall (ufw)"
    sudo ufw allow 80/tcp comment 'PlayOS PXE HTTP' || true
    sudo ufw allow 69/udp comment 'PlayOS PXE TFTP' || true
    sudo ufw allow 67/udp comment 'PlayOS PXE DHCP proxy' || true
fi

# ── iPXE USB stick fallback (optional helper) ────────────────────────────
echo ""
echo "==> Creating iPXE USB image (optional fallback for WiFi-only clients)"
mkdir -p "$ROOT/out"
USB_IMG="$ROOT/out/playos-ipxe-usb.img"
if command -v truncate >/dev/null 2>&1 && command -v mkfs.vfat >/dev/null 2>&1; then
    # Create a small FAT image with embedded iPXE script
    rm -f "$USB_IMG"
    truncate -s 64M "$USB_IMG"
    mkfs.vfat -F32 -n PLAYOS_PXE "$USB_IMG" >/dev/null 2>&1

    # Mount and copy ipxe.efi + embedded script
    USB_MNT=$(mktemp -d)
    sudo mount -o loop "$USB_IMG" "$USB_MNT"
    sudo mkdir -p "$USB_MNT/EFI/BOOT"

    # Copy iPXE as the default UEFI boot loader
    sudo cp "$IPXE_EFI" "$USB_MNT/EFI/BOOT/BOOTX64.EFI"

    # Create an embedded iPXE script that chain-loads from HTTP
    sudo tee "$USB_MNT/EFI/BOOT/boot.ipxe" > /dev/null <<IPXESCRIPT
#!ipxe
set server ${SERVER_IP}
chain http://\${server}${PLAYOS_URL_BASE}/boot.ipxe
IPXESCRIPT

    sudo umount "$USB_MNT"
    rmdir "$USB_MNT"
    sudo chown "$(id -u):$(id -g)" "$USB_IMG"

    echo "    USB image: $USB_IMG"
    echo "    Write it with: sudo dd if=$USB_IMG of=/dev/sdX bs=4M status=progress conv=fsync"
else
    echo "    Skipped (missing truncate or mkfs.vfat)"
fi

# ── Verify ───────────────────────────────────────────────────────────────
echo ""
echo "=== PXE Server Setup Complete ==="
echo ""
echo "Server IP : $SERVER_IP"
echo "HTTP      : http://$SERVER_IP$PLAYOS_URL_BASE/"
echo "TFTP root : $TFTP_ROOT"
echo "Boot chain: PXE → ipxe.efi (TFTP) → boot.ipxe (TFTP) → HTTP fetch"
echo ""
echo "Verify with: curl -sI http://$SERVER_IP$PLAYOS_URL_BASE/boot.ipxe | head -5"
echo ""
echo "Next steps:"
echo "  1. Run: bash scripts/build-iso-ubuntu.sh  (if not done already)"
echo "  2. Boot a UEFI client with PXE (wired Ethernet required)"
echo "  3. Or use USB fallback: $USB_IMG"
echo ""
echo "Troubleshooting:"
echo "  sudo journalctl -u dnsmasq -f    # Watch DHCP/PXE requests"
echo "  sudo tail -f /var/log/nginx/access.log  # Watch HTTP requests"
