title   PlayOS (safe mode — console only, no GPU)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=512M systemd.unit=multi-user.target
